### PR TITLE
various details, mostly about doc formatting

### PR DESCRIPTION
**Pull request by fchapoton**
changing to the standard shape `EXAMPLES::`

also some comparisons to None and True are modified

### CODE REVIEW

**Comment by fchapoton** [comment]
hmm, why merge in master and not in develop ? This is a bit annoying, as I work on develop.

**Comment by fredstro** [comment]
Sorry, I just clicked the merge button without checking which branch you had selected to merge with...

**Comment by fchapoton** [comment]
oh, sorry, my fault then

**Comment by fredstro** [comment]
well, I should also check what I am doing...

**Pull request merged**
